/*
 * PanelIndices.java
 *
 * Created on 24 de noviembre de 2008, 16:33
 */

package radiadores.igu;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import radiadores.entidades.Cargo;

/**
 *
 * @author  Lisandro
 */
public class PanelIndices extends javax.swing.JDialog {

    /** Creates new form PanelIndices */
    public PanelIndices() {
        initComponents();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tConceptos = new org.jdesktop.swingx.JXTable();
        btCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfLiquidez = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCreditoDias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCreditosProveedores = new javax.swing.JTextField();
        tfRotacionInversiones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfRentabilidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfRendimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tComposicionVentas = new org.jdesktop.swingx.JXTable();
        tfUnidadesRechazadas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfBajasVoluntarias = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Conceptos Y Valores"));

        tConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Disponibilidad", "20000"},
                {"Realizable a corto plazo", "5000"},
                {"Pasivo Corriente", "1500"},
                {"Cuentas por Cobrar", "2500"},
                {"Promedio de cobro", "1000"},
                {"Pasivo a corto plazo", "21600"},
                {"Deudas que contraigo por día", "720"},
                {"Ventas", "90533"},
                {"Activo Total", "54600"},
                {"Utilidades", "32000"},
                {"Ventas del producto(a)", "3"},
                {"Ventas del producto(b)", "2"},
                {"Ventas del producto(c)", "2"},
                {"Ventas totales", "45"},
                {"Unidades rechazadas", "0"},
                {"Unidades totales producidas", "45"},
                {"Número de bajas voluntarias", "1"},
                {"Total de Personal", "6"}
            },
            new String [] {
                "Concepto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tConceptos);

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCalcular))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculos"));

        jLabel3.setText("Liquidez : ");

        tfLiquidez.setEditable(false);

        jLabel4.setText("Nivel De Credito (dias) : ");

        tfCreditoDias.setEditable(false);

        jLabel5.setText("Nivel De Credito (Proveedores) : ");

        tfCreditosProveedores.setEditable(false);

        tfRotacionInversiones.setEditable(false);

        jLabel6.setText("Rotacion de las Inversiones : ");

        jLabel7.setText("Rentabilidad : ");

        tfRentabilidad.setEditable(false);

        jLabel8.setText("Rendimiento : ");

        tfRendimiento.setEditable(false);

        jLabel9.setText("Composicion De La Ventas : ");

        tComposicionVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", null},
                {"B", null},
                {"C", null}
            },
            new String [] {
                "Producto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tComposicionVentas.setEditable(false);
        jScrollPane2.setViewportView(tComposicionVentas);

        tfUnidadesRechazadas.setEditable(false);

        jLabel13.setText("Unidades Rechazas : ");

        jLabel15.setText("Numeros de Bajas Voluntarias : ");

        tfBajasVoluntarias.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRentabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfCreditoDias, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfCreditosProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfRotacionInversiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfLiquidez, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfRendimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUnidadesRechazadas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tfBajasVoluntarias, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel3)
                    .addComponent(tfLiquidez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfCreditoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfCreditosProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfRotacionInversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel8)
                    .addComponent(tfRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfUnidadesRechazadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfBajasVoluntarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

    
    
    
    
    
    
    Double resulLiquidez = (Double.valueOf(this.tConceptos.getValueAt(0,1).toString())+Double.valueOf(this.tConceptos.getValueAt(1,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(2,1).toString());
    this.tfLiquidez.setText(resulLiquidez.toString());
    
    Double resultCuotas = (Double.valueOf(this.tConceptos.getValueAt(3,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(4,1).toString());
    this.tfCreditoDias.setText(resultCuotas.toString());
    
    Double resulPro = (Double.valueOf(this.tConceptos.getValueAt(5,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(6,1).toString());
    this.tfCreditosProveedores.setText(resulPro.toString());
    
    Double resulRotacion = (Double.valueOf(this.tConceptos.getValueAt(7,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(8,1).toString());
    this.tfRotacionInversiones.setText(resulRotacion.toString());
    
    Double resulRentab = (Double.valueOf(this.tConceptos.getValueAt(9,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(8,1).toString());
    this.tfRentabilidad.setText(resulRentab.toString());
    
    Double resulRend = (Double.valueOf(this.tConceptos.getValueAt(9,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(7,1).toString());
    this.tfRendimiento.setText(resulRend.toString());

    Double resulVtaProdA = (Double.valueOf(this.tConceptos.getValueAt(10,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(13,1).toString());
    this.tComposicionVentas.setValueAt(resulVtaProdA, 0, 1);
            
    Double resulVtaProdB = (Double.valueOf(this.tConceptos.getValueAt(11,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(13,1).toString());
    this.tComposicionVentas.setValueAt(resulVtaProdB, 1, 1);

    Double resulVtaProdC = (Double.valueOf(this.tConceptos.getValueAt(12,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(13,1).toString());
    this.tComposicionVentas.setValueAt(resulVtaProdC, 2, 1);

    //aca los agrego al datamodel...
        
    
    Double resulCalidad = (Double.valueOf(this.tConceptos.getValueAt(14,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(15,1).toString());
    this.tfUnidadesRechazadas.setText(resulCalidad.toString());

    Double resulClima = (Double.valueOf(this.tConceptos.getValueAt(16,1).toString()))/Double.valueOf(this.tConceptos.getValueAt(17,1).toString());
    this.tfBajasVoluntarias.setText(resulClima.toString());
    
    
    
    
}//GEN-LAST:event_btCalcularActionPerformed


  public static void main(String[] args) throws ClassNotFoundException, InstantiationException,
            IllegalAccessException, UnsupportedLookAndFeelException {
        
        
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        System.setProperty("apple.laf.useScreenMenuBar", "true");
        
        
        PanelIndices p = new PanelIndices();
        
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        
        new Thread() {
            @Override
            public void run() {
            //    FachadaPersistencia.getInstancia().buscar(Cargo.class,
            //            "SELECT c FROM Cargo c WHERE 0 > 1");
            }
            
        }.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tComposicionVentas;
    private org.jdesktop.swingx.JXTable tConceptos;
    private javax.swing.JTextField tfBajasVoluntarias;
    private javax.swing.JTextField tfCreditoDias;
    private javax.swing.JTextField tfCreditosProveedores;
    private javax.swing.JTextField tfLiquidez;
    private javax.swing.JTextField tfRendimiento;
    private javax.swing.JTextField tfRentabilidad;
    private javax.swing.JTextField tfRotacionInversiones;
    private javax.swing.JTextField tfUnidadesRechazadas;
    // End of variables declaration//GEN-END:variables

}
